"""unique score content version

Revision ID: 9697fc113dc0
Revises: 69906a39172f
Create Date: 2026-08-15 13:42:55.844865

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9697fc113dc0"
down_revision: str | Sequence[str] | None = "69906a39172f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_score_contents_score_version", "score_contents", ["score_id", "version"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_score_contents_score_version", "score_contents", type_="unique")
    # ### end Alembic commands ###
